// HTML output formatting for execution results
use super::result::ExecutionResult;

/// Format execution result as a complete HTML report
pub fn to_html_output(result: &ExecutionResult) -> String {
    let mut html = String::new();

    // HTML head
    html.push_str("<!DOCTYPE html>\n");
    html.push_str("<html lang=\"en\">\n");
    html.push_str("<head>\n");
    html.push_str("  <meta charset=\"UTF-8\">\n");
    html.push_str("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.push_str("  <title>Test Report - web-spec</title>\n");
    html.push_str(&generate_css());
    html.push_str("</head>\n");
    html.push_str("<body>\n");

    // Header
    html.push_str("  <header class=\"header\">\n");
    html.push_str("    <div class=\"container\">\n");
    html.push_str("      <h1>Test Execution Report</h1>\n");
    html.push_str("      <p class=\"timestamp\">Generated at ");
    html.push_str(&result.timestamp);
    html.push_str("</p>\n");
    html.push_str("    </div>\n");
    html.push_str("  </header>\n");

    // Summary panel
    html.push_str(&generate_summary_panel(result));

    // Feature info
    html.push_str(&generate_feature_info(result));

    // Scenarios
    html.push_str(&generate_scenarios(result));

    // Footer
    html.push_str("  <footer class=\"footer\">\n");
    html.push_str("    <div class=\"container\">\n");
    html.push_str("      <p>Generated by web-spec | Test Anything Protocol</p>\n");
    html.push_str("    </div>\n");
    html.push_str("  </footer>\n");

    html.push_str("</body>\n");
    html.push_str("</html>\n");

    html
}

/// Generate CSS styles for the HTML report
fn generate_css() -> String {
    let mut css = String::new();

    css.push_str("  <style>\n");
    css.push_str("    * {\n");
    css.push_str("      margin: 0;\n");
    css.push_str("      padding: 0;\n");
    css.push_str("      box-sizing: border-box;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    body {\n");
    css.push_str("      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;\n");
    css.push_str("      background-color: #f5f7fa;\n");
    css.push_str("      color: #2c3e50;\n");
    css.push_str("      line-height: 1.6;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .container {\n");
    css.push_str("      max-width: 1200px;\n");
    css.push_str("      margin: 0 auto;\n");
    css.push_str("      padding: 0 20px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .header {\n");
    css.push_str("      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
    css.push_str("      color: white;\n");
    css.push_str("      padding: 40px 0;\n");
    css.push_str("      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .header h1 {\n");
    css.push_str("      font-size: 2.5em;\n");
    css.push_str("      margin-bottom: 10px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .timestamp {\n");
    css.push_str("      font-size: 0.9em;\n");
    css.push_str("      opacity: 0.9;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    main {\n");
    css.push_str("      padding: 40px 0;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .summary-panel {\n");
    css.push_str("      display: grid;\n");
    css.push_str("      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n");
    css.push_str("      gap: 20px;\n");
    css.push_str("      margin-bottom: 40px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .summary-card {\n");
    css.push_str("      background: white;\n");
    css.push_str("      padding: 20px;\n");
    css.push_str("      border-radius: 8px;\n");
    css.push_str("      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .summary-card h3 {\n");
    css.push_str("      font-size: 0.85em;\n");
    css.push_str("      color: #7f8c8d;\n");
    css.push_str("      margin-bottom: 10px;\n");
    css.push_str("      text-transform: uppercase;\n");
    css.push_str("      letter-spacing: 1px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .summary-value {\n");
    css.push_str("      font-size: 2.5em;\n");
    css.push_str("      font-weight: bold;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .status-passed { color: #27ae60; }\n");
    css.push_str("    .status-failed { color: #e74c3c; }\n");
    css.push_str("    .status-skipped { color: #f39c12; }\n");
    css.push_str("    .status-pending { color: #95a5a6; }\n");
    css.push_str("\n");
    css.push_str("    .feature-section {\n");
    css.push_str("      background: white;\n");
    css.push_str("      padding: 30px;\n");
    css.push_str("      border-radius: 8px;\n");
    css.push_str("      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n");
    css.push_str("      margin-bottom: 40px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .feature-header {\n");
    css.push_str("      display: flex;\n");
    css.push_str("      justify-content: space-between;\n");
    css.push_str("      align-items: center;\n");
    css.push_str("      margin-bottom: 20px;\n");
    css.push_str("      padding-bottom: 20px;\n");
    css.push_str("      border-bottom: 2px solid #ecf0f1;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .feature-header h2 {\n");
    css.push_str("      font-size: 1.8em;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .status-badge {\n");
    css.push_str("      display: inline-block;\n");
    css.push_str("      padding: 6px 12px;\n");
    css.push_str("      border-radius: 20px;\n");
    css.push_str("      font-weight: bold;\n");
    css.push_str("      font-size: 0.9em;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .badge-passed {\n");
    css.push_str("      background-color: #d4edda;\n");
    css.push_str("      color: #155724;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .badge-failed {\n");
    css.push_str("      background-color: #f8d7da;\n");
    css.push_str("      color: #721c24;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .badge-pending {\n");
    css.push_str("      background-color: #e2e3e5;\n");
    css.push_str("      color: #383d41;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .feature-meta {\n");
    css.push_str("      display: grid;\n");
    css.push_str("      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n");
    css.push_str("      gap: 20px;\n");
    css.push_str("      margin-bottom: 30px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .meta-item {\n");
    css.push_str("      padding: 12px;\n");
    css.push_str("      background-color: #f8f9fa;\n");
    css.push_str("      border-left: 4px solid #667eea;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .meta-label {\n");
    css.push_str("      font-size: 0.85em;\n");
    css.push_str("      color: #7f8c8d;\n");
    css.push_str("      margin-bottom: 4px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .meta-value {\n");
    css.push_str("      font-weight: 600;\n");
    css.push_str("      word-break: break-all;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .scenarios-list {\n");
    css.push_str("      display: flex;\n");
    css.push_str("      flex-direction: column;\n");
    css.push_str("      gap: 20px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .scenario-item {\n");
    css.push_str("      border-left: 4px solid #e8e8e8;\n");
    css.push_str("      padding: 15px 20px;\n");
    css.push_str("      background-color: #f8f9fa;\n");
    css.push_str("      border-radius: 4px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .scenario-item.passed {\n");
    css.push_str("      border-left-color: #27ae60;\n");
    css.push_str("      background-color: #f0fdf4;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .scenario-item.failed {\n");
    css.push_str("      border-left-color: #e74c3c;\n");
    css.push_str("      background-color: #fef2f2;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .scenario-item.skipped {\n");
    css.push_str("      border-left-color: #f39c12;\n");
    css.push_str("      background-color: #fffbf0;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .scenario-header {\n");
    css.push_str("      display: flex;\n");
    css.push_str("      justify-content: space-between;\n");
    css.push_str("      align-items: center;\n");
    css.push_str("      margin-bottom: 10px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .scenario-title {\n");
    css.push_str("      font-weight: 600;\n");
    css.push_str("      font-size: 1.05em;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .scenario-duration {\n");
    css.push_str("      font-size: 0.85em;\n");
    css.push_str("      color: #7f8c8d;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .steps-list {\n");
    css.push_str("      margin-top: 12px;\n");
    css.push_str("      padding-left: 20px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .step-item {\n");
    css.push_str("      display: flex;\n");
    css.push_str("      align-items: flex-start;\n");
    css.push_str("      margin-bottom: 8px;\n");
    css.push_str("      padding: 6px 0;\n");
    css.push_str("      font-size: 0.95em;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .step-icon {\n");
    css.push_str("      display: inline-block;\n");
    css.push_str("      width: 20px;\n");
    css.push_str("      margin-right: 10px;\n");
    css.push_str("      text-align: center;\n");
    css.push_str("      flex-shrink: 0;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .step-content {\n");
    css.push_str("      flex: 1;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .step-text {\n");
    css.push_str("      color: #2c3e50;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .step-error {\n");
    css.push_str("      background-color: #fee;\n");
    css.push_str("      border-left: 3px solid #e74c3c;\n");
    css.push_str("      padding: 8px 12px;\n");
    css.push_str("      margin-top: 6px;\n");
    css.push_str("      border-radius: 3px;\n");
    css.push_str("      font-size: 0.9em;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .error-message {\n");
    css.push_str("      color: #721c24;\n");
    css.push_str("      margin-bottom: 6px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .error-suggestions {\n");
    css.push_str("      list-style: none;\n");
    css.push_str("      padding-left: 0;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .error-suggestions li {\n");
    css.push_str("      padding: 4px 0;\n");
    css.push_str("      font-size: 0.85em;\n");
    css.push_str("      color: #721c24;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .error-suggestions li:before {\n");
    css.push_str("      content: \"• \";\n");
    css.push_str("      margin-right: 6px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .step-output {\n");
    css.push_str("      background-color: #f8f9fa;\n");
    css.push_str("      border: 1px solid #dee2e6;\n");
    css.push_str("      padding: 8px 12px;\n");
    css.push_str("      margin-top: 6px;\n");
    css.push_str("      border-radius: 3px;\n");
    css.push_str("      font-family: 'Monaco', 'Courier New', monospace;\n");
    css.push_str("      font-size: 0.85em;\n");
    css.push_str("      color: #495057;\n");
    css.push_str("      overflow-x: auto;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    .footer {\n");
    css.push_str("      background-color: #2c3e50;\n");
    css.push_str("      color: #ecf0f1;\n");
    css.push_str("      text-align: center;\n");
    css.push_str("      padding: 20px 0;\n");
    css.push_str("      margin-top: 40px;\n");
    css.push_str("    }\n");
    css.push_str("\n");
    css.push_str("    @media (max-width: 768px) {\n");
    css.push_str("      .header h1 { font-size: 1.8em; }\n");
    css.push_str("      .summary-panel { grid-template-columns: 1fr; }\n");
    css.push_str("      .feature-meta { grid-template-columns: 1fr; }\n");
    css.push_str("      .feature-header { flex-direction: column; align-items: flex-start; }\n");
    css.push_str("      .status-badge { margin-top: 10px; }\n");
    css.push_str("    }\n");
    css.push_str("  </style>\n");

    css
}

/// Generate the summary panel with statistics
fn generate_summary_panel(result: &ExecutionResult) -> String {
    let mut html = String::new();
    let summary = &result.summary;

    html.push_str("  <main class=\"container\">\n");
    html.push_str("    <div class=\"summary-panel\">\n");

    // Overall status
    let overall_class = match result.status.as_str() {
        "passed" => "status-passed",
        "failed" => "status-failed",
        _ => "status-pending",
    };
    html.push_str("      <div class=\"summary-card\">\n");
    html.push_str("        <h3>Overall Status</h3>\n");
    html.push_str(&format!(
        "        <div class=\"summary-value {}\">{}</div>\n",
        overall_class,
        result.status.to_uppercase()
    ));
    html.push_str("      </div>\n");

    // Scenarios
    html.push_str("      <div class=\"summary-card\">\n");
    html.push_str("        <h3>Scenarios</h3>\n");
    html.push_str("        <div class=\"summary-value\">");
    html.push_str(&format!(
        "{}/{}",
        summary.passed_scenarios + summary.failed_scenarios,
        summary.total_scenarios
    ));
    html.push_str("</div>\n");
    html.push_str(&format!("        <p><span class=\"status-passed\">✓ {}</span> | <span class=\"status-failed\">✗ {}</span> | <span class=\"status-skipped\">⊘ {}</span></p>\n",
        summary.passed_scenarios, summary.failed_scenarios, summary.skipped_scenarios));
    html.push_str("      </div>\n");

    // Steps
    html.push_str("      <div class=\"summary-card\">\n");
    html.push_str("        <h3>Steps</h3>\n");
    html.push_str("        <div class=\"summary-value\">");
    html.push_str(&format!(
        "{}/{}",
        summary.passed_steps + summary.failed_steps,
        summary.total_steps
    ));
    html.push_str("</div>\n");
    html.push_str(&format!("        <p><span class=\"status-passed\">✓ {}</span> | <span class=\"status-failed\">✗ {}</span> | <span class=\"status-skipped\">⊘ {}</span></p>\n",
        summary.passed_steps, summary.failed_steps, summary.skipped_steps));
    html.push_str("      </div>\n");

    // Duration
    html.push_str("      <div class=\"summary-card\">\n");
    html.push_str("        <h3>Duration</h3>\n");
    html.push_str(&format!("        <div class=\"summary-value\">{}<span style=\"font-size: 0.5em;\">ms</span></div>\n", result.duration_ms));
    html.push_str("      </div>\n");

    html.push_str("    </div>\n");

    html
}

/// Generate feature information section
fn generate_feature_info(result: &ExecutionResult) -> String {
    let mut html = String::new();

    html.push_str("    <div class=\"feature-section\">\n");

    // Feature header
    html.push_str("      <div class=\"feature-header\">\n");
    html.push_str(&format!(
        "        <h2>{}</h2>\n",
        escape_html(&result.feature.name)
    ));
    let badge_class = match result.status.as_str() {
        "passed" => "badge-passed",
        "failed" => "badge-failed",
        _ => "badge-pending",
    };
    html.push_str(&format!(
        "        <span class=\"status-badge {}\">{}</span>\n",
        badge_class,
        result.status.to_uppercase()
    ));
    html.push_str("      </div>\n");

    // Feature metadata
    html.push_str("      <div class=\"feature-meta\">\n");

    if let Some(file) = &result.feature.file {
        html.push_str("        <div class=\"meta-item\">\n");
        html.push_str("          <div class=\"meta-label\">FILE</div>\n");
        html.push_str(&format!(
            "          <div class=\"meta-value\">{}</div>\n",
            escape_html(file)
        ));
        html.push_str("        </div>\n");
    }

    html.push_str("        <div class=\"meta-item\">\n");
    html.push_str("          <div class=\"meta-label\">DURATION</div>\n");
    html.push_str(&format!(
        "          <div class=\"meta-value\">{}ms</div>\n",
        result.duration_ms
    ));
    html.push_str("        </div>\n");

    html.push_str("        <div class=\"meta-item\">\n");
    html.push_str("          <div class=\"meta-label\">TIMESTAMP</div>\n");
    html.push_str(&format!(
        "          <div class=\"meta-value\">{}</div>\n",
        result.timestamp
    ));
    html.push_str("        </div>\n");

    html.push_str("      </div>\n");

    if let Some(desc) = &result.feature.description {
        if !desc.is_empty() {
            html.push_str("      <div style=\"margin-top: 20px; padding: 15px; background-color: #f8f9fa; border-left: 4px solid #667eea; border-radius: 4px;\">\n");
            html.push_str("        <p><strong>Description:</strong></p>\n");
            html.push_str(&format!("        <p>{}</p>\n", escape_html(desc)));
            html.push_str("      </div>\n");
        }
    }

    html.push_str("    </div>\n");

    html
}

/// Generate scenarios section
fn generate_scenarios(result: &ExecutionResult) -> String {
    let mut html = String::new();

    html.push_str("    <div class=\"feature-section\">\n");
    html.push_str("      <h3>Scenarios</h3>\n");
    html.push_str("      <div class=\"scenarios-list\">\n");

    for (idx, scenario) in result.scenarios.iter().enumerate() {
        let scenario_class = &scenario.status;
        html.push_str(&format!(
            "        <div class=\"scenario-item {}\">\n",
            scenario_class
        ));

        html.push_str("          <div class=\"scenario-header\">\n");
        html.push_str(&format!(
            "            <div class=\"scenario-title\">{}. {}</div>\n",
            idx + 1,
            scenario.name
        ));
        html.push_str(&format!(
            "            <div class=\"scenario-duration\">{}ms</div>\n",
            scenario.duration_ms
        ));
        html.push_str("          </div>\n");

        // Steps
        html.push_str("          <div class=\"steps-list\">\n");
        for (_step_idx, step) in scenario.steps.iter().enumerate() {
            let symbol = match step.status.as_str() {
                "passed" => "✓",
                "failed" => "✗",
                "skipped" => "⊘",
                _ => "?",
            };

            html.push_str("            <div class=\"step-item\">\n");
            html.push_str(&format!(
                "              <div class=\"step-icon\">{}</div>\n",
                symbol
            ));
            html.push_str("              <div class=\"step-content\">\n");
            html.push_str(&format!(
                "                <div class=\"step-text\"><strong>{}</strong> {}</div>\n",
                step.keyword,
                escape_html(&step.text)
            ));

            if let Some(error) = &step.error {
                html.push_str("                <div class=\"step-error\">\n");
                html.push_str(&format!(
                    "                  <div class=\"error-message\">Error: {}</div>\n",
                    escape_html(&error.message)
                ));
                if !error.suggestions.is_empty() {
                    html.push_str("                  <ul class=\"error-suggestions\">\n");
                    for suggestion in &error.suggestions {
                        html.push_str(&format!(
                            "                    <li>{}</li>\n",
                            escape_html(suggestion)
                        ));
                    }
                    html.push_str("                  </ul>\n");
                }
                html.push_str("                </div>\n");
            }

            if let Some(output) = &step.output {
                if !output.is_empty() {
                    html.push_str(&format!(
                        "                <div class=\"step-output\">{}</div>\n",
                        escape_html(output)
                    ));
                }
            }

            html.push_str("              </div>\n");
            html.push_str("            </div>\n");
        }
        html.push_str("          </div>\n");

        html.push_str("        </div>\n");
    }

    html.push_str("      </div>\n");
    html.push_str("    </div>\n");
    html.push_str("  </main>\n");

    html
}

/// Escape HTML special characters
fn escape_html(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::execution::{FeatureInfo, ScenarioResult, StepResult};

    #[test]
    fn test_html_output_basic_structure() {
        let feature = FeatureInfo {
            name: "Test Feature".to_string(),
            file: Some("test.feature".to_string()),
            description: Some("A test feature".to_string()),
        };
        let result = ExecutionResult::new(feature);
        let html = to_html_output(&result);

        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("Test Feature"));
        assert!(html.contains("Test Execution Report"));
        assert!(html.contains("</html>"));
    }

    #[test]
    fn test_html_output_with_scenarios() {
        let feature = FeatureInfo {
            name: "Test Feature".to_string(),
            file: Some("test.feature".to_string()),
            description: None,
        };
        let mut result = ExecutionResult::new(feature);

        let mut scenario = ScenarioResult {
            name: "Test Scenario".to_string(),
            status: "passed".to_string(),
            duration_ms: 1000,
            steps: Vec::new(),
        };

        let step = StepResult {
            text: "I click on button".to_string(),
            keyword: "Given".to_string(),
            status: "passed".to_string(),
            duration_ms: 500,
            output: None,
            error: None,
        };

        scenario.steps.push(step);
        result.add_scenario(scenario);

        let html = to_html_output(&result);

        assert!(html.contains("Test Scenario"));
        assert!(html.contains("I click on button"));
        assert!(html.contains("Given"));
    }

    #[test]
    fn test_html_output_escapes_html_characters() {
        let feature = FeatureInfo {
            name: "Test Feature <script>".to_string(),
            file: Some("test<>.feature".to_string()),
            description: Some("A test & feature".to_string()),
        };
        let result = ExecutionResult::new(feature);
        let html = to_html_output(&result);

        assert!(html.contains("Test Feature &lt;script&gt;"));
        assert!(html.contains("test&lt;&gt;.feature"));
        assert!(html.contains("A test &amp; feature"));
    }

    #[test]
    fn test_html_output_with_failed_step() {
        let feature = FeatureInfo {
            name: "Test Feature".to_string(),
            file: None,
            description: None,
        };
        let mut result = ExecutionResult::new(feature);

        let mut scenario = ScenarioResult {
            name: "Test Scenario".to_string(),
            status: "failed".to_string(),
            duration_ms: 1500,
            steps: Vec::new(),
        };

        let step = StepResult {
            text: "I click on missing button".to_string(),
            keyword: "When".to_string(),
            status: "failed".to_string(),
            duration_ms: 1000,
            output: Some("Browser timeout".to_string()),
            error: Some(crate::execution::ErrorInfo {
                code: "ELEMENT_NOT_FOUND".to_string(),
                message: "Element not found".to_string(),
                suggestions: vec!["Try using a different selector".to_string()],
            }),
        };

        scenario.steps.push(step);
        result.add_scenario(scenario);
        result.status = "failed".to_string();

        let html = to_html_output(&result);

        assert!(html.contains("failed"));
        assert!(html.contains("Element not found"));
        assert!(html.contains("Try using a different selector"));
        assert!(html.contains("Browser timeout"));
    }

    #[test]
    fn test_html_output_summary_section() {
        let feature = FeatureInfo {
            name: "Test Feature".to_string(),
            file: None,
            description: None,
        };
        let result = ExecutionResult::new(feature);
        let html = to_html_output(&result);

        assert!(html.contains("Overall Status"));
        assert!(html.contains("Scenarios"));
        assert!(html.contains("Steps"));
        assert!(html.contains("Duration"));
        assert!(html.contains("summary-panel"));
    }
}
